export const projects = [
    {
      img: "https://www.advisoryhq.com/wp-content/uploads/2019/11/rodan-and-fields-reviews-min.png",
      title: "Rodan + Feilds",
      des: "It is american multilevel marketing company specialized in skincare products,Rodan + Fields is a leading skincare brand founded in 2000 by Stanford-trained Dermatologists Dr. Katie Rodan and Dr. Kathy Fields with a passion for giving people the best skin of their lives — and the confidence that comes with it.",
      demo: "",
      live: "https://glittering-duckanoo-b64d5f.netlify.app/",
      gitHub: "https://github.com/NarayandasGanesh/innate-van-5165/tree/main/my-app",
      technologies: [
        "Tech Stacks :",
        "React",
        "Redux",
        "Material Ui",
        "Node js",
        "Chakra",
      ],
    },
    {
      img: "https://i.pcmag.com/imagery/reviews/06GdAglsVsGlkBgtUw4Dtwb-9..v1609778483.png",
      title: "Airtable.com",
      des: "At its core, Airtable allows you to easily create a database that holds the information that matters for your work, then use it to power the visualizations, processes, and integrations that make up a custom application that's truly unique to you.This is group project with 4 members.",
      demo: "",
      live: "https://stellar-concha-5c9a19.netlify.app/",
      gitHub: "https://github.com/medadeshreyas/Airtable.com-Clone",
      technologies: [
        "Tech Stacks :",
        "HTML",
        "Css",
        "Javascript",
        "Bootstrap",
      ],
    },
    {
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqbWJdWOWqog7Nh9o1NvN_O8pKJRyvuQdwsMarIX5SjrLlM_-3pPyLeIBrXU9Tbs_Q56Y&usqp=CAU",
      title: "FRAAZO.com",
      des: "FRAAZO is the best online vegetables, fruits & grocery ordering app with over 1.5Mn+ happy customers. We provide the largest variety of farm-fresh",
      demo: "",
      live: "https://shiny-cupcake-6dab31.netlify.app/",
      gitHub: "https://github.com/saurabhrana7699/frazoo-clone",
      technologies: [
        "Tech Stacks :",
        "HTML",
        "Css",
        "Javascript",
        "Bootstrap",
      ],
    },
    {
      img: "https://i.pinimg.com/236x/3e/1c/30/3e1c30c1ed967290320eff1c475c4b45.jpg",
      title: "PLURAL SIGHT",
      des: "5 team member's Top-rated courses for developers & IT professionals. Start learning today with Pluralsight. On-demand training made simple. #1 training for individuals and businesses! Mobile Apps",
      demo: "",
      live: "https://incredible-hummingbird-0080a2.netlify.app/",
      gitHub: "https://github.com/arpitmiahra4/plural-project",
      technologies: [
        "Tech Stacks :",
        "HTML",
        "Css",
        "Javascript",
        "Bootstrap",
      ],
    },
  ];